import random #to import the random module for randomly generating characters from the list of characters

class passwordgenerator(): #defining the class passwordgenerator

    def __init__(self, passwords, characters, listOfCharacters): #defining the constructor and data members for the class

        self.passwords = passwords
        self.characters = characters
        self.listOfCharacters = listOfCharacters

    def create_password(self): #defining the method for generating password
        
        
        for i in self.characters: #defining a loop to go inside the characters so that the loop variable is then appended inside the list

            self.listOfCharacters.append(i) #appending all the characters inside the listOfCharacters list
        
        number = int(input("Enter how many characters you want inside your password:" )) #variable to actually ask the user how many number of characters he/she needs within his/her password

        for i in range(number): #defining a loop to go inside the range of values stored within the number variable

            self.passwords = self.passwords + random.choice(self.listOfCharacters) #updating the password variable with new password

        print("Your random generated password is: " , self.passwords) #displaying out the random password generated by the method

password_object = passwordgenerator("", "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890!@#$%^&*()_-+=|\'[]{}:;'""<>.,/?~`", []) #creating a new object for the class
password_object.create_password() #accessing the method inside the class using the object

